### ISSUE TITLE
y-indexeddb does not set the correct origin on initial load

### ISSUE THREAD

**Issue by yufw** [yjs/y-indexeddb#17]
**Describe the bug**
On initial load using y-indexeddb, `event.transaction.origin` is null and `event.transaction.local` is true.

**To Reproduce**
1. Create a basic example that uses y-indexeddb provider and `ymap.observe(event => { console.log(event) })` to see the event on initial load.

**Expected behavior**
The expected behavior is that `event.transaction.origin` should be the provider and `event.transaction.local` is set to false (because it is coming from a provider? not sure about the expected behavior here)

**Environment Information**
 - Chrome
 - yjs v13.4.9, y-indexeddb v9.0.6

**Comment by dmonad** [comment]
Thanks for this! I fixed it and will release a new version shortly.
