### ISSUE TITLE
observe does not work for Y.Map of Y.Arrays

### ISSUE THREAD

**Issue by eberberich** [yjs/y-indexeddb#41]
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**

The observe callback for (a) nested Y.Array(s) in a Y.Map is not executed when indexeddb persistence is in place.

**To Reproduce**

Run the attached minimal example [persistence-problem.zip](https://github.com/user-attachments/files/16612236/persistence-problem.zip)

* ``npm install``
* ``npm run dev``
* Open http://localhost:5173/
  * The div showing the length goes up (the console shows that ``yArray.observe`` callback is executed) - with every interval callback in the code
* Uncomment the line ``// const persistence = new IndexeddbPersistence(dbName, ydoc);``
  * Page automatically reloads (vite) - all works as before
  * Reload the page multiple times
    * The yArray starts from an empty array now, instead of adding to the existing array
    * Most of the time the div showing the length is stuck now (you can see in the console, that the callback is NOT called anymore) - sometimes the counting up works - but still: always starts from an empty array

Search in ``index.js`` for PROBLEM 1/2/3 to find the code places

**Expected behavior**

The observe callbacks for the nested arrays work, and the nested arrays do not start from scratch upon page reloads!

**Environment Information**
 - Browser: Firefox 128
 - "y-indexeddb": "9.0.12", "yjs": "13.6.18"

* [x] This issue is a blocker for my project.

**Comment by eberberich** [comment]
Here is a video 

https://github.com/user-attachments/assets/c2668655-e1d8-422e-8b73-6334d0fac544

**Comment by eberberich** [comment]
Any ideas here?

**Comment by dmonad** [comment]
I looked through the source code of your app (which I normally don't do), and it seems that you are overwriting the data on every load. You register event listeners on Y.Arrays that you overwrite when you enable persistence.
