### ISSUE TITLE
Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### ISSUE THREAD

**Issue by ilya2204** [yjs/y-indexeddb#42]
Hi, we use y-indexeddb in our project and in sentry we see the following error in a very small percentage of users, but after it, users lose data from yDoc (probably because nothing is actually saved). Most users catch it on mobile safari, but it sometimes occurs in chrome too. We can't reproduce it, it's super rare. Maybe we should add some error handling?

`Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.`

Stack trace shows this line:
![image](https://github.com/user-attachments/assets/0e70c233-b415-4ec8-81bf-9f21bc74b066)

Maybe this is related to https://github.com/yjs/y-indexeddb/pull/13

**Comment by dmonad** [comment]
This probably happens because the YIndexedDBProvider is destroyed. This closes the database. 

Providers get implicitly destroyed when you call `ydoc.destroy()`.

Without more information, this ticket is not actionable.

**Comment by ilya2204** [comment]
Ok, i'll investigate the guess with document destroy. But just for reference, [AFFiNE](https://github.com/toeverything/AFFiNE) also faces such a problem and apparently there are also suspicions on mobile safari https://github.com/toeverything/AFFiNE/issues/7598

**Comment by tclxdongyang-guo** [comment]
have the same error
