### ISSUE TITLE
CommonJS require doesn't work

### ISSUE THREAD

**Issue by brechtcs** [yjs/y-indexeddb#7]
This is not really a blocking issue, but for quick prototyping I often still use CommonJS instead of ESM imports. For all the other `yjs` modules I've used so far this works fine, but with this one Browserify is giving me the dreaded `ParseError: 'import' and 'export' may appear only with 'sourceType: module'`.

**Comment by dmonad** [comment]
Hi @brechtcs , this is fixed in v9.0.3. Thanks for the PR!
