### ISSUE TITLE
Failed to execute 'put' on 'IDBObjectStore': The parameter is not a valid key

### ISSUE THREAD

**Issue by KrishnaPG** [yjs/y-indexeddb#9]
**Describe the bug**
`IndexeddbPersistence.set()` method has problems.

Checkout this line of code https://github.com/yjs/y-indexeddb/blob/2d21bdfc8ba7e862148f574cb1ce79c25c025e1b/src/y-indexeddb.js#L152

and then check this definition of `put` method from lib0: 
````
export const put = (store, item, key) =>
  rtop(store.put(item, key))
````
https://github.com/dmonad/lib0/blob/8a89d8d369c9dccd1187a75c04232e2a1ce39b7b/indexeddb.js#L126

The `lib0` is expecting `item` followed by `key` as parameters, while the `set` call in this package is sending `key` first and then `value` next, which is leading to the error:

![image](https://user-images.githubusercontent.com/4610831/87247369-1a4fb000-c471-11ea-8526-0fe5fa94bf15.png)
````
Failed to execute 'put' on 'IDBObjectStore': The parameter is not a valid key
````

**Comment by dmonad** [comment]
Thanks for noticing. Fixed it
